name: Backend test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - run: npm ci
        working-directory: ./backend
      - run: npm run build
        working-directory: ./backend
      - run: npm run lint
        working-directory: ./backend
      - run: npm run test
        working-directory: ./backend
