name: Backend test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        working-directory: ./backend
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run test
