name: Backend Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code and set working directory
        uses: actions/checkout@v3
        with:
          path: ${{ inputs.working-directory }}

      - name: Use Node.js ${{ matrix.node-version }} and set working directory
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        working-directory: ${{ inputs.working-directory }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.working-directory }}

      - name: Build
        run: npm run build --if-present
        working-directory: ${{ inputs.working-directory }}

      - name: Linting
        run: npm run lint
        working-directory: ${{ inputs.working-directory }}

      - name: Run tests
        run: npm run test
        working-directory: ${{ inputs.working-directory }}
